services:
  bot:
    container_name: bt-bot
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      - postgres
      - pgadmin
    tty: true

  postgres:
    container_name: bt-pg
    image: postgres
    hostname: localhost
    ports:
      - "3004:3004"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPORT: ${POSTGRES_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - transfer:/var/transfer:rw
    restart: unless-stopped

  pgadmin:
    container_name: bt-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    restart: unless-stopped
    volumes:
      - transfer:/var/lib/pgadmin:rw

volumes:
  postgres-data:
  transfer:
